from .classification import categorical_cross_entropy, binary_cross_entropy
from .classification import bayesian_crossentropy_lin_wrapper, bayesian_crossentropy_var_wrapper
from .regression import mean_absolute_percentage_error, mean_squared_logarithmic_error
from .regression import mean_squared_error, mse_lin_wrapper, mse_var_wrapper, mean_absolute_error
from .vae_loss import nll
